"""Testing

Revision ID: 396050429ccb
Revises: eddc403b40b5
Create Date: 2026-07-05 20:33:58.792293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '396050429ccb'
down_revision: Union[str, Sequence[str], None] = 'eddc403b40b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('company', sa.String(), nullable=False))
    op.drop_column('applications', 'company_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('applications', 'company')
    # ### end Alembic commands ###
